spring.application.name=digital-construction-passport

server.port=8080

spring.datasource.url=jdbc:sqlite:passport.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.security.jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS
app.security.jwt.ttl-seconds=3600
